#!/bin/bash

# Set language
sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
export LANG=en_US.UTF-8

# Set time zone
ln -s /usr/share/zoneinfo/US/Central /etc/localtime
hwclock --systohc --utc

# Enable networking
systemctl enable dhcpcd@en01.service

# Install a few needed things
pacman -S grub

# Create ramdisk environment
mkinitcpio -p linux

# Set root password
passwd

# Install bootloader
grub-install --target=i386-pc --recheck /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

# Install some things we need
pacman -S vim openssh cmake wget git

# Enable wheel group to have sudo
sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers

# Don't allow root login for ssh
sed -i 's/# PermitRootLogin.*/PermitRootLogin no/g' /etc/ssh/sshd_config

# Enable ssh
systemctl enable sshd

# Add users
for user in wes du hank kun alex lalit bin; do
	useradd -m -G wheel -s /bin/bash $user
	mkdir /data/$user
	chown -R $user:user /data/$user
	ln -s /data/$user /home/$user/data
done

exit
