#!/bin/bash

set -e

# Install some things we need
pacman -q -S --noconfirm vim openssh cmake git mlocate zsh screen xorg-server fftw

# Update locate database
updatedb

# Enable wheel group to have sudo
echo "Enabling wheel group in sudoers..."
sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers

# Enable ssh
systemctl enable sshd

rm /etc/resolv.conf
ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf

useradd -m -G wheel -s /bin/bash wes
passwd wes
