#!/bin/bash
# Arch install script for cluster
# Make sure internet is connected!

# Partition the disks
sgdisk -o /dev/sda
sgdisk -n 1:2048:+200M -c 1:"Linux /boot" -t 1:8300 /dev/sda
sgdisk -n 2:+0M:+20G -c 2:"Linux /" -t 2:8300 /dev/sda
sgdisk -n 3:+0M:+15G -c 3:"Linux /var" -t 2:8300 /dev/sda
sgdisk -n 4 -c 4:"Linux /home" -t 4:8300 /dev/sda
sgdisk -n 5 -c 5:"BIOS boot partition" -t 5:ef02 /dev/sda

# Extra disk
sgdisk -o /dev/sdb
sgdisk -n 1 -c 1:"Linux /data" -t 1:8300 /dev/sdb

# Format the partitions
mkfs.ext4 /dev/sda1
mkfs.ext4 /dev/sda2
mkfs.ext4 /dev/sda3
mkfs.ext4 /dev/sda4
mkfs.ext4 /dev/sdb1

# Mount the partitions (mount root first)
mount /dev/sda2 /mnt
mkdir -p /mnt/boot
mount /dev/sda1 /mnt/boot
mkdir -p /mnt/var
mount /dev/sda3 /mnt/var
mkdir -p /mnt/home
mount /dev/sda4 /mnt/home
mkdir -p /mnt/data
mount /dev/sdb1 /mnt/data

# Install base system
pacstrap -i /mnt base base-devel

# Make sure disks are automounted
genfstab -U -p /mnt >> /mnt/etc/fstab

wget
https://raw.githubusercontent.com/wesbarnett/cluster/master/install-master-part2
chmod +x install-master-part2
cp install-master-2 /mnt/

echo "You are now entering chroot environment. Run ./arch-install-2 to continue"
# Base system is installed, now change to it and run postinstall script there
arch-chroot /mnt /bin/bash
