#!/bin/bash
# Arch install script for NAS with four disks, RAID-5

PART2=install-nas-part2
GITHUB=https://raw.githubusercontent.com/wesbarnett/cluster/master

modprobe raid1
modprobe raid5
modprobe dm-mod

sgdisk -og /dev/sda 
sgdisk -n 1:2048:+100M -c 1:"Linux /boot" -t 1:fd00 /dev/sda
sgdisk -n 2 -c 2:"Linux /" -t 2:fd00 /dev/sda

sgdisk --backup=table /dev/sda
gdisk --load-backup=table /dev/sdb
gdisk --load-backup=table /dev/sdc
gdisk --load-backup=table /dev/sdd

mdadm --create /dev/md0 --level=5 --raid-devices=4 /dev/sd[abcd]2
mdadm --create /dev/md1 --level=1 --raid-devices=4 --metadata=1.0 /dev/sd[abcd]1

pvcreate /dev/md0
vgcreate VolGroupArray /dev/md0
lvcreate -L 20G VolGroupArray -n lvroot
lvcreate -L 15G VolGroupArray -n lvvar
lvcreate -l +100%FREE VolGroupArray -n lvhome

mkfs.ext4 /dev/VolGroupArray/lvroot
mkfs.ext4 /dev/VolGroupArray/lvvar
mkfs.ext4 /dev/VolGroupArray/lvhome
mkfs.ext4 /dev/md1

mount /dev/VolGroupArray/lvroot /mnt
mkdir -p /mnt/boot
mount /dev/md1 /mnt/boot
mkdir -p /mnt/home
mount /dev/VolGroupArray/lvhome /mnt/home
mkdir -p /mnt/var
mount /dev/VolGroupArray/lvvar /mnt/var

echo "Installing base system..."
pacstrap /mnt base base-devel

# Make sure disks are automounted
echo "Generating fstab..."
genfstab -U -p /mnt >> /mnt/etc/fstab

echo "Getting part 2..."
wget $GITHUB/$PART2
chmod +x $PART2
cp $PART2 /mnt/

echo "You are now entering chroot environment. Run ./$PART2 to continue"
# Base system is installed, now change to it and run postinstall script there
arch-chroot /mnt /bin/bash
