#!/bin/bash

set -e

NODE=2
INTERFACE=eno1
USERS="wes du hank kun asaltzm lalit bmeng natalia"

########################

MYHOSTNAME=node$NODE

if [[ `whoami` != "root" ]]; then
  echo "This script must be run as root or with sudo."
  exit
fi


# Set language
sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
export LANG=en_US.UTF-8

# Set time zone
ln -s /usr/share/zoneinfo/US/Central /etc/localtime
hwclock --systohc --utc

# Set hostname
echo $MYHOSTNAME > /etc/hostname

# Enable networking
systemctl enable dhcpcd@en01.service

# Install a few needed things
pacman -S grub

# Create ramdisk environment
mkinitcpio -p linux

# Set root password
passwd

# Install bootloader
grub-install --target=i386-pc --recheck /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

# Install some things we need to mount pacman cache
pacman -S nfs-utils

# Sets up networking with static ip
cat - > /etc/net-conf-$INTERFACE <<CONFIG
address=192.168.0.$NODE
netmask=24
broadcast=192.168.0.255
gateway=192.168.0.1
CONFIG

cat - > /etc/systemd/system/network@.service <<CONFIG
[Unit]
Description=Network connectivity (%i)
Wants=network.target
Before=network.target
BindsTo=sys-subsystem-net-devices-%i.device
After=sys-subsystem-net-devices-%i.device

[Service]
Type=oneshot
RemainAfterExit=yes
EnvironmentFile=/etc/conf.d/net-conf-%i

ExecStart=ip link set dev %i up
ExecStart=ip addr add \${address}/\${netmask} broadcast \${broadcast} dev %i
ExecStart=[[ -z \${gateway} ]] || { ip route add default via \${gateway} }

ExecStop=ip addr flush dev %i
ExecStop=ip route flush dev %i
ExecStop=ip link set dev %i down

[Install]
WantedBy=multi-user.target
CONFIG

systemctl enable network@$INTERFACE
systemctl start network@$INTERFACE

# Enable nfs
systemctl start rpcbind.service
systemctl enable rpcbind.service
systemctl start nfs-server.service
systemctl enable nfs-server.service

read -p "Plug ethernet cable into master node. Then press any key to continue... " -n1 -s

# Setup pacman cache share mount
mkdir -p /mnt/pacmancache
echo "master:/srv/nfs4/networkcache /var/cache/pacman/pkg nfs noauto,noatime,rsize=32768,wsize=32768 0 0" >> /etc/fstab

mount -t nfs master:/srv/nfs4/networkcache/ /var/cache/pacman/pkg

# Install some things we need
pacman -S vim openssh cmake wget git locate zsh screen xorg-server fftw

# Update locate database
updatedb

# Enable wheel group to have sudo
sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers

# Enable ssh
systemctl enable sshd

# Add users
for user in $USERS; do
	useradd -m -G wheel -s /bin/bash $user
	mkdir /data/$user
	chown -R $user:$user /data/$user
	passwd $user
	chage -d 0 $user
done

exit
