#!/bin/bash
 
# James W. Barnett <jbarnet4@tulane.edu>

# Script for creating tmux session with window panes connected to each node
# (very similar to 'clusterssh' program without all of the dependencies, and you
# don't need an X server).  Input is synchronized, so you type one command in,
# and it is entered on every node. Assumes nodes are in /etc/hosts as node2,
# node3, etc.

NNODES=12

################################

SESSION="clusterssh"

which tmux 2>/dev/null 1>&2

if [[ $? -eq 1 ]]; then
    echo "tmux was not found, and is required. Install tmux before running"
    echo "again." 
    exit
fi

tmux has-session -t $SESSION
if [[ $? -eq 0 ]]; then
    echo "A cluster management session already exists! You should attached to"
    echo "that one first, or rename it, before proceeding." 
    exit
fi

tmux new-session -s $SESSION -d 'ssh node2' 2>/dev/null 1>&2

for ((i=$NNODES;i>=3;i--)); do
    tmux split-window -t $SESSION -d 'ssh node'$i'' 2>/dev/null 1>&2
    tmux select-layout -t $SESSION tiled 2>/dev/null 1>&2
done

tmux set-window-option synchronize-panes on 2>/dev/null 1>&2

tmux attach
